name: CI/CD Pipeline

on:
  push:
    branches:
      - dev   # Trigger only on dev branch
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/team-zeta-zenith-backend" ]; then
              git clone https://github.com/${{ github.repository }}.git team-zeta-zenith-backend
            fi
            cd team-zeta-zenith-backend
            git fetch --all
            git reset --hard origin/dev

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
      
            docker compose pull

            docker network rm zenith_network || true
            
            docker compose up -d --build --remove-orphans
